# Generated by Django 5.0.1 on 2024-02-16 18:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_image_text'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='caketype',
            new_name='cake_type',
        ),
    ]
