# Generated by Django 5.0.1 on 2024-02-17 18:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0007_about'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='about',
            new_name='values',
        ),
    ]
